import { Translation } from './types';

export const APP_NAME = "منصة التعلم الإلكتروني الجزائرية";

export const TEXT_TRANSLATIONS: Translation = {
  appName: { ar: "منصة التعلم الإلكتروني الجزائرية", fr: "Plateforme d'apprentissage en ligne algérienne" },
  home: { ar: "الرئيسية", fr: "Accueil" },
  login: { ar: "تسجيل الدخول", fr: "Connexion" },
  register: { ar: "إنشاء حساب", fr: "Inscription" },
  dashboard: { ar: "لوحة التحكم", fr: "Tableau de bord" },
  channels: { ar: "القنوات", fr: "Chaînes" },
  profile: { ar: "الملف الشخصي", fr: "Profil" },
  logout: { ar: "تسجيل الخروج", fr: "Déconnexion" },
  darkMode: { ar: "الوضع الليلي", fr: "Mode Sombre" },
  lightMode: { ar: "الوضع النهاري", fr: "Mode Jour" },
  language: { ar: "اللغة", fr: "Langue" },
  arabic: { ar: "العربية", fr: "Arabe" },
  french: { ar: "الفرنسية", fr: "Français" },
  professor: { ar: "أستاذ", fr: "Professeur" },
  student: { ar: "طالب", fr: "Étudiant" },
  email: { ar: "البريد الإلكتروني", fr: "Email" },
  password: { ar: "كلمة المرور", fr: "Mot de passe" },
  fullName: { ar: "الاسم الكامل", fr: "Nom Complet" },
  nationalUniversity: { ar: "الجامعة الوطنية", fr: "Université Nationale" },
  facultyDepartment: { ar: "الكلية والقسم", fr: "Faculté et Département" },
  registerAs: { ar: "التسجيل كـ", fr: "S'inscrire en tant que" },
  alreadyHaveAccount: { ar: "هل لديك حساب بالفعل؟", fr: "Vous avez déjà un compte ?" },
  dontHaveAccount: { ar: "ليس لديك حساب؟", fr: "Vous n'avez pas de compte ?" },
  createChannel: { ar: "إنشاء قناة", fr: "Créer une chaîne" },
  channelName: { ar: "اسم القناة", fr: "Nom de la chaîne" },
  channelDescription: { ar: "وصف القناة", fr: "Description de la chaîne" },
  department: { ar: "القسم", fr: "Département" },
  uploadContent: { ar: "تحميل محتوى", fr: "Télécharger du contenu" },
  pdf: { ar: "ملف PDF", fr: "Fichier PDF" },
  image: { ar: "صورة", fr: "Image" },
  video: { ar: "فيديو", fr: "Vidéo" },
  addMeetLink: { ar: "إضافة رابط Google Meet", fr: "Ajouter un lien Google Meet" },
  meetLink: { ar: "رابط Google Meet", fr: "Lien Google Meet" },
  publishAnnouncement: { ar: "نشر إعلان", fr: "Publier une annonce" },
  announcementTitle: { ar: "عنوان الإعلان", fr: "Titre de l'annonce" },
  announcementContent: { ar: "محتوى الإعلان", fr: "Contenu de l'annonce" },
  myChannels: { ar: "قنواتي", fr: "Mes chaînes" },
  mySubscribedChannels: { ar: "قنواتي المشترك بها", fr: "Mes chaînes abonnées" },
  myFollowedProfessors: { ar: "الأساتذة الذين أتابعهم", fr: "Mes professeurs suivis" },
  viewChannel: { ar: "عرض القناة", fr: "Voir la chaîne" },
  subscribe: { ar: "اشترك", fr: "S'abonner" },
  price: { ar: "السعر", fr: "Prix" },
  dzd: { ar: "د.ج", fr: "DZD" },
  stars: { ar: "نجوم", fr: "Étoiles" },
  subscribers: { ar: "مشتركون", fr: "Abonnés" },
  content: { ar: "المحتوى", fr: "Contenu" },
  chatWithProfessor: { ar: "الدردشة مع الأستاذ", fr: "Discuter avec le professeur" },
  send: { ar: "إرسال", fr: "Envoyer" },
  typeYourMessage: { ar: "اكتب رسالتك...", fr: "Écrivez votre message..." },
  settings: { ar: "الإعدادات", fr: "Paramètres" },
  changeProfilePicture: { ar: "تغيير الصورة الشخصية", fr: "Changer la photo de profil" },
  changeEmail: { ar: "تغيير البريد الإلكتروني", fr: "Changer l'email" },
  changePhoneNumber: { ar: "تغيير رقم الهاتف", fr: "Changer le numéro de téléphone" },
  currentPassword: { ar: "كلمة المرور الحالية", fr: "Mot de passe actuel" },
  newPassword: { ar: "كلمة المرور الجديدة", fr: "Nouveau mot de passe" },
  updateProfile: { ar: "تحديث الملف الشخصي", fr: "Mettre à jour le profil" },
  jarvisAssistant: { ar: "مساعد جارفيس", fr: "Assistant Jarvis" },
  askJarvis: { ar: "اسأل جارفيس...", fr: "Demandez à Jarvis..." },
  loading: { ar: "جاري التحميل...", fr: "Chargement..." },
  noContent: { ar: "لا يوجد محتوى حالياً.", fr: "Pas de contenu pour le moment." },
  noChannels: { ar: "لا توجد قنوات بعد.", fr: "Pas encore de chaînes." },
  followProfessor: { ar: "تابع الأستاذ", fr: "Suivre le professeur" },
  unfollowProfessor: { ar: "إلغاء متابعة الأستاذ", fr: "Ne plus suivre le professeur" },
  paymentSuccess: { ar: "تم الاشتراك بنجاح! سيتم إرسال تأكيد إلى بريدك الإلكتروني.", fr: "Abonnement réussi ! Une confirmation sera envoyée à votre email." },
  paymentFailed: { ar: "فشل الاشتراك. يرجى المحاولة مرة أخرى.", fr: "Échec de l'abonnement. Veuillez réessayer." },
  readMore: { ar: "اقرأ المزيد", fr: "Lire la suite" },
  viewDetails: { ar: "عرض التفاصيل", fr: "Voir les détails" },
  availableChannels: { ar: "القنوات المتاحة", fr: "Chaînes disponibles" },
  myAnnouncements: { ar: "إعلاناتي", fr: "Mes annonces" },
  myMessages: { ar: "رسائلي", fr: "Mes messages" },
  selectUniversity: { ar: "اختر الجامعة", fr: "Sélectionner l'université" },
  selectFaculty: { ar: "اختر الكلية", fr: "Sélectionner la faculté" },
  selectDepartment: { ar: "اختر القسم", fr: "Sélectionner le département" },
  enterMeetLink: { ar: "أدخل رابط Google Meet", fr: "Entrez le lien Google Meet" },
  editChannel: { ar: "تعديل القناة", fr: "Modifier la chaîne" },
  updateChannel: { ar: "تحديث القناة", fr: "Mettre à jour la chaîne" },
  confirmDelete: { ar: "هل أنت متأكد أنك تريد حذف هذه القناة؟", fr: "Êtes-vous sûr de vouloir supprimer cette chaîne ?" },
  delete: { ar: "حذف", fr: "Supprimer" },
  cancel: { ar: "إلغاء", fr: "Annuler" },
  professorNotFound: { ar: "لم يتم العثور على الأستاذ.", fr: "Professeur introuvable." },
  messageSent: { ar: "تم إرسال الرسالة.", fr: "Message envoyé." },
  failedToSend: { ar: "فشل إرسال الرسالة.", fr: "Échec de l'envoi du message." },
  toggleChat: { ar: "تبديل الدردشة", fr: "Basculer le chat" },
  jarvisDescription: { ar: "مساعدك الذكي للإجابة على أسئلتك في البيئة الجزائرية وتقديم مصادر موثوقة.", fr: "Votre assistant intelligent pour répondre à vos questions dans le contexte algérien et fournir des sources fiables." },
  aiResponseError: { ar: "حدث خطأ أثناء الحصول على رد من الذكاء الاصطناعي.", fr: "Une erreur est survenue lors de l'obtention de la réponse de l'IA." },
  enterPrompt: { ar: "أدخل استفسارك...", fr: "Entrez votre question..." },
  noSources: { ar: "لا توجد مصادر متاحة.", fr: "Aucune source disponible." },
  sources: { ar: "المصادر", fr: "Sources" },
  updateSuccessful: { ar: "تم التحديث بنجاح!", fr: "Mise à jour réussie !" },
  updateFailed: { ar: "فشل التحديث.", fr: "Échec de la mise à jour." },
  fileUploadError: { ar: "خطأ في تحميل الملف: ", fr: "Erreur de téléchargement de fichier : " },
  fileUploadSuccess: { ar: "تم تحميل الملف بنجاح!", fr: "Fichier téléchargé avec succès !" },
  noMessages: { ar: "لا توجد رسائل.", fr: "Aucun message." },
  noAnnouncements: { ar: "لا توجد إعلانات بعد.", fr: "Aucune annonce pour le moment." },
  selectOption: { ar: "اختر خياراً", fr: "Sélectionner une option" },
  chatHistory: { ar: "سجل الدردشة", fr: "Historique du chat" },
  aiDisclaimer: {ar: "جارفيس هو مساعد ذكاء اصطناعي. قد تكون إجابته غير دقيقة أحياناً.", fr: "Jarvis est un assistant IA. Ses réponses peuvent parfois être inexactes."},
  selectApiKey: {ar: "يرجى تحديد مفتاح API الخاص بك للمتابعة.", fr: "Veuillez sélectionner votre clé API pour continuer."},
  openApiKeySelection: {ar: "فتح اختيار مفتاح API", fr: "Ouvrir la sélection de clé API"},
  billingInfo: {ar: "لمزيد من المعلومات حول الفوترة، تفضل بزيارة", fr: "Pour plus d'informations sur la facturation, visitez"},
  apiWarning: {ar: "تتطلب هذه الميزة مفتاح API مدفوعًا.", fr: "Cette fonctionnalité nécessite une clé API payante."}
};

export const UNIVERSITIES = [
  { id: 'univ-alger1', name: { ar: 'جامعة الجزائر 1', fr: 'Université d\'Alger 1' } },
  { id: 'univ-alger2', name: { ar: 'جامعة الجزائر 2', fr: 'Université d\'Alger 2' } },
  { id: 'univ-alger3', name: { ar: 'جامعة الجزائر 3', fr: 'Université d\'Alger 3' } },
  { id: 'univ-oran1', name: { ar: 'جامعة وهران 1', fr: 'Université d\'Oran 1' } },
  { id: 'univ-constantine1', name: { ar: 'جامعة قسنطينة 1', fr: 'Université de Constantine 1' } },
];

export const FACULTIES = [
  { id: 'comp-sci', name: { ar: 'علوم الحاسوب', fr: 'Informatique' } },
  { id: 'med', name: { ar: 'الطب', fr: 'Médecine' } },
  { id: 'law', name: { ar: 'الحقوق', fr: 'Droit' } },
  { id: 'lit', name: { ar: 'الآداب', fr: 'Lettres' } },
];

export const DEPARTMENTS = [
  { id: 'cs-ai', name: { ar: 'ذكاء اصطناعي', fr: 'Intelligence Artificielle' } },
  { id: 'cs-sw', name: { ar: 'هندسة برمجيات', fr: 'Génie Logiciel' } },
  { id: 'med-gen', name: { ar: 'طب عام', fr: 'Médecine Générale' } },
  { id: 'law-pub', name: { ar: 'قانون عام', fr: 'Droit Public' } },
];
